### ISSUE TITLE
Modal not working on Firefox

### ISSUE THREAD

**Issue by stebogit** [ResponsiveBP/Responsive#104]
Hi,
I found that the `Modal` feature (I'm only using that part of the library) doesn't work on Firefox (`v57.0b5 (64-bit)`) due to this [non-standard](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-device-pixel-ratio) line of the stylesheet, which embraces the css handling the hiding/showing of the modal layer:
```css
@media (-webkit-min-device-pixel-ratio: 0) { 
    ...
}
```
Surprised nobody encountered the same issue so far.

However, I removed that line and it seems to work just fine.

**Comment by JimBobSquarePants** [comment]
Hi @stebogit, 

Thanks for raising this, in answer to your statement:

>Surprised nobody encountered the same issue so far.

I would say that is probably because they are not using a beta release.  

The non-standard code you are seeing is a hack to specifically filter out Webkit browsers and will affect select inputs. 

https://github.com/ResponsiveBP/Responsive/blob/061ef2803142a50152c1402749ca66b438afb833/src/sass/partials/_forms.scss#L223

In the latest stable this appears to be fine.

![modal-firefox](https://user-images.githubusercontent.com/385879/31208282-8632b610-a9cf-11e7-80eb-52062f1dcce1.jpg)

I'd like to see what happens when a final v57 release is out since I believe they have updated the parsing engine for that. 

Let's keep this open and track what happens.

Cheers

James

**Comment by JimBobSquarePants** [comment]
Confirmed to be working perfectly in Firefox 57 64bit. I'm not sure what the cause of your issue is but it's not the default CSS.

![modal-firefox](https://user-images.githubusercontent.com/385879/32814387-fcd49ed4-ca02-11e7-826d-e863755faf2e.jpg)
