### ISSUE TITLE
css position "x" above-right the lightbox

### ISSUE THREAD

**Issue by basemwahba** [ResponsiveBP/Responsive#91]
Hi,

Thanks for the great framework.

I have tried to position the lightbox-close "x" above-right the lightbox by editing css, but I did't succeed.

Example from mailchimp popup form:

![2016-09-23_15-34-45](https://cloud.githubusercontent.com/assets/14953296/18787740/64f40a52-81a4-11e6-9460-30d7ec4aacbe.png)

May you please advise regarding this/

Thanks

**Comment by JimBobSquarePants** [comment]
Hi @basemwahba 

Apologies for the slow response. The model is specifically designed to make that difficult since moving the close button to that location is an anti pattern as it provides a poor user experience. 

Think about it like this. If the `X` or `Close` is positioned inline with the model contents it will change position on resizing the browser or toggling through a model gallery. This can become confusing to the user. They have to rescan the page to find the button, changing mouse position or their thumb depending on viewport.

I hope that is clear.

Cheers

James

**Comment by basemwahba** [comment]
Hi,

No apology at all. Thanks so much for your reply. Thanks also for your clarifications.

Best Regards
