### ISSUE TITLE
Divs overlap when using off-set

### ISSUE THREAD

**Issue by sphaero** [ResponsiveBP/Responsive#94]
See https://jsfiddle.net/amy10wdc/3/

This seems caused by left: 8.333% in the offset class. If instead margin-left is used it doesn't happen.

Tested on Firefox 45.5.1

**Comment by JimBobSquarePants** [comment]
Hi @sphaero apologies for the slow reply.

That's actually by design. If you look at the documentation for [offset](http://responsivebp.com/css/grid/#offsetting) you will see that there is a requirement for adding the classes to multiple columns to offset. 

In the future V5 I do plan to improve the grid by providing both flexbox and grid specification versions. 

https://github.com/ResponsiveBP/Responsive/issues/92
